# Generated by Django 3.1.7 on 2021-05-27 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataMentah',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('longitude', models.DecimalField(decimal_places=4, max_digits=7)),
                ('latitude', models.DecimalField(decimal_places=4, max_digits=6)),
                ('altitude', models.DecimalField(decimal_places=3, max_digits=7)),
                ('altitude1', models.DecimalField(decimal_places=3, max_digits=7)),
                ('suhu_udara', models.DecimalField(decimal_places=2, max_digits=4)),
                ('suhu_baterai', models.DecimalField(decimal_places=2, max_digits=4)),
                ('kelembaban_udara', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tekanan_udara', models.DecimalField(decimal_places=2, max_digits=6)),
                ('suhu_cpu', models.DecimalField(decimal_places=2, max_digits=4)),
                ('status_layar', models.BooleanField()),
                ('status_charging', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'data mentah',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserAndroid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField()),
                ('model', models.CharField(max_length=12)),
                ('api_version', models.CharField(max_length=12)),
            ],
            options={
                'verbose_name_plural': 'user_android',
            },
        ),
        migrations.CreateModel(
            name='DataMatang',
            fields=[
                ('data_mentah', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='data_matang', serialize=False, to='apiServer.datamentah', verbose_name='data_mentah related')),
                ('suhu_udara', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('kelembaban_udara', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('tekanan_udara', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
            ],
            options={
                'verbose_name_plural': 'data matang',
            },
        ),
        migrations.AddConstraint(
            model_name='userandroid',
            constraint=models.UniqueConstraint(fields=('uuid', 'model'), name='unique_user_android'),
        ),
        migrations.AddField(
            model_name='datamentah',
            name='user_android',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_mentah', to='apiServer.userandroid', verbose_name='user_android yang merekam'),
        ),
        migrations.AddConstraint(
            model_name='datamentah',
            constraint=models.UniqueConstraint(fields=('user_android', 'timestamp'), name='unique_data_mentah'),
        ),
    ]
