# Generated by Django 3.1.7 on 2021-06-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiServer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userandroid',
            name='model',
            field=models.CharField(max_length=20),
        ),
    ]
